"""add_fk_user_id_on_cart_items_and_orders

Revision ID: 1409d4f8b2bd
Revises: 
Create Date: 2026-03-13 03:19:00.394743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1409d4f8b2bd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'cart_items', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    # ### end Alembic commands ###
